# Generated by Django 4.2.16 on 2025-04-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id_deceased', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_born', models.DateTimeField(blank=True, null=True)),
                ('date_death', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('burial_place', models.CharField(blank=True, max_length=100, null=True)),
                ('visualization_state', models.BooleanField(default=True)),
                ('visualization_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'TBL_DECEASED',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'TBL_USER',
                'managed': False,
            },
        ),
    ]
