# Generated by Django 5.2 on 2025-04-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mausoleum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id_image', models.BigAutoField(primary_key=True, serialize=False)),
                ('link_image', models.CharField(max_length=255)),
                ('event_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'TBL_IMAGE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id_video', models.BigAutoField(primary_key=True, serialize=False)),
                ('link_video', models.CharField(max_length=255)),
                ('event_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'TBL_VIDEO',
                'managed': False,
            },
        ),
    ]
